config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'

  devise_for :users
  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :patients, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :consultations, only: [:new, :create]
  end
  resources :consultations, only: [:show] do
    resources :prescriptions, only: [:new, :create]
  end

  resources :medicines, only: [:index, :show, :new, :create, :update]

  resources :prescriptions, only: [:show] do
    resources :prescription_medicines
    resources :medical_procedures, only: [:create, :new]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  # resources :medical_procedures, only: [:show]
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :consultation
  has_many :prescription_medicines
  has_many :medicines, through: :prescription_medicines
  has_many :medical_procedures
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :find_prescription, only: [:show]

  def show
    @medical_procedure = MedicalProcedure.new
    @prescription_medicine = PrescriptionMedicine.new
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "file_name", template: "prescriptions/show", formats: [:html]  # Excluding ".pdf" extension.
      end
    end
  end

  def new
    @consultation = Consultation.find(params[:consultation_id])
    @prescription = Prescription.create(consultation_id: @consultation.id)
  end

  def create
    @consultation = Consultation.find(params[:consultation_id])
    @prescription = Prescription.new(consultation_id: params[:consultation_id])
    if @prescription.save
      redirect_to prescription_path(@prescription)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def find_prescription
    @prescription = Prescription.find(params[:id])
  end
end

app/views/prescriptions/new.html.erb
<h1>New Prescription</h1>

<%# <%= link_to 'Créer un nouveau médicament', medicines_new_path %>
<%# <%= simple_form_for @prescription do |f| %>
        <%# <%= f.input :name %>
        <%# <%= f.input :NR %>
        <%# <%= f.submit "Ajouter du contenu", class: "btn btn-primary" %>
    <%# <% end %>

<p><%= link_to 'Créer une procédure médicale ', new_medical_procedure_path %></p>
    <%= simple_form_for [@consultation, @prescription] do |f| %>
        <%= f.input :content %>
        <%= f.submit "Ajouter du contenu", class: "btn btn-primary" %>
    <% end %>

app/views/prescriptions/show.html.erb
<h1>Prescription details</h1>

<p class= "text-right"><%= @prescription.created_at %></p>
    <div>
      <% @prescription.medical_procedures.each do |f| %>
        <p><%= f.content %></p>
      <% end %>
    </div>
    <%= simple_form_for [@prescription, @medical_procedure] do |f| %>
        <%= f.input :content %>
        <%= f.submit "Ajouter une procédure", class: "btn-grad font" %>
    <% end %>

    <div>
      <%= @prescription.prescription_medicines.each do |f| %>
        <p><%= f.duration %></p>
        <p><%= f.dosage %></p>
      <% end %>
    </div>

  <%= simple_form_for [@prescription, @prescription_medicine] do |f| %>

        <%= f.input :medicine_id, collection: Medicine.all, label_method: :name_form_medicine %>
        <div class = "try">
        <p>Lundi</p><p> Mardi</p> <p> Mercredi </p><p> Jeudi</p><p> Vendredi </p> <p> Samedi </p><p> Dimanche </p>
        </div>
        <div class = "wrapper">
        <%= f.collection_check_boxes :daily_take, DailyTake.all, :id, :day_time %>
        </div>
        <%= f.input :duration %>
        <%= f.input :dosage %>
        <%= f.submit "Ajouter une prescription", class: "btn-grad font" %>
    <% end %>

<%= link_to 'Acceuil', root_path, class: "btn-grad font" %>