config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'

  devise_for :users
  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :patients, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :consultations, only: [:new, :create]
  end
  resources :consultations, only: [:show] do
    resources :prescriptions, only: [:new, :create]
  end

  resources :medicines, only: [:index, :show, :new, :create, :update]

  resources :prescriptions, only: [:show] do
    resources :prescription_medicines
    resources :medical_procedures, only: [:create, :new]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  # resources :medical_procedures, only: [:show]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag "https://res.cloudinary.com/dvinewomn/image/upload/v1678456522/logo1_h3mapx.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%# <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          <%# </li> %>
          <li class="nav-item">
            <%= link_to 'Dashboard', dashboard_path, class: "nav-link"%>
          </li>
          <li>
            <%= link_to 'Nouveau Patient', new_patient_path, class: "nav-link"%>
          </li>
          <li>
            <%# <%= link_to 'Consultation', new_patient_consultation_path, class:"nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://img.freepik.com/premium-vector/doctor-icon-avatar-white_136162-58.jpg?w=240", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>