config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'

  devise_for :users
  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :patients, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :consultations, only: [:new, :create]
  end
  resources :consultations, only: [:show] do
    resources :prescriptions, only: [:new, :create]
  end

  resources :medicines, only: [:index, :show, :new, :create, :update]

  resources :prescriptions, only: [:show] do
    resources :prescription_medicines
    resources :medical_procedures, only: [:create, :new]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  # resources :medical_procedures, only: [:show]
end

app/views/pages/dashboard.html.erb
<div class="container">

  <div class="title">
    <h2>Dashboard</h2>
  </div>

  <div class="name">
    <h1>👋 Bonjour! Dr. <%= current_user.last_name %>.</h1>
  </div>

<div class="row justify-content-center">
  <div class="searchbar col-md-10">
    <%= form_with url: dashboard_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Patient"
      %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
    <div class="row justify-content-center">
      <div class="col-sm-8">
        <div class="card-product">
          <% @patients.each do |patient| %>
            <%= link_to patient_path(patient.id) do %>
              <div class="card-product-infos">
                <%= image_tag "avatar_patient.png" %>
                <h2><%= patient.last_name %></h2>
                <h2><%= patient.first_name %></h2>
                <p><%= patient.social_security_number %></p>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="container">
<div class="row">
<div class="col">
<h1>SALUTIS</h1>
<p>Health Medical Record</p>
<p>in your pocket</p>
</div>
</div>
</div>