config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'

  devise_for :users
  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :patients, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :consultations, only: [:new, :create]
  end
  resources :consultations, only: [:show] do
    resources :prescriptions, only: [:new, :create]
  end

  resources :medicines, only: [:index, :show, :new, :create, :update]

  resources :prescriptions, only: [:show] do
    resources :prescription_medicines
    resources :medical_procedures, only: [:create, :new]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  # resources :medical_procedures, only: [:show]
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :chatrooms
  has_many :consultations
  has_many :doctors, through: :consultations, class_name: 'User'

  GENDERS = ["masculin", "féminin"]

  validates :first_name, :last_name, :birthday, :social_security_number, presence: true
  validates :height, :weight, :gender, presence: true
  validates :birthday, comparison: { less_than: Date.today }
  validates :social_security_number, length: { is: 15 }
  validates :social_security_number, uniqueness: true
  validates :height, numericality: true
  validates :weight, numericality: true
  validates :gender, inclusion: { in: GENDERS, message: "n'apparait pas dans la liste" }

  include PgSearch::Model
  pg_search_scope :search_by_first_name_and_last_name_and_social_security_number,
  against: [ :first_name, :last_name, :social_security_number ],
  using: {
    tsearch: { prefix: true }
  }
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
    @patient = Patient.all
  end

  def show
    # find_user
    @consultations = @patient.consultations
        # if params[:consulation].present?
    @chatroom = Chatroom.find_by_patient_id(@patient.id)
    unless @chatroom
      @chatroom = Chatroom.create(patient_id: @patient.id)
    end
  end

  def edit
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(params_patients)
    if @patient.save
      Chatroom.create(patient_id: @patient.id)
      redirect_to patient_path(@patient)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    # find_user
    if @patient.update(params_patients)
      redirect_to patient_path(@patient)
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    # find_user
    @patient.destroy
    render :show
  end

  private

  def params_patients
    params.require(:patient).permit(
      :first_name, :last_name, :birthday, :social_security_number,
      :pathology, :height, :weight, :gender
    )
  end

  def find_user
    @patient = Patient.find(params[:id])
  end
end

app/views/patients/edit.html.erb
<div class="container">
 <div class="row">
    <div class="col">
      <%= simple_form_for @patient do |f| %>
        <%= f.input :first_name, placeholder: "Prénom(s)" %>
        <%= f.input :last_name, placeholder: "Nom(s) de famille" %>
        <%= f.input :birthday, placeholder: "YYYY/mm/dd" %>
        <%= f.input :social_security_number, placeholder: "Numéro de sécurité social" %>
        <%= f.input :pathology, placeholder: "ALD" %>
        <%= f.input :height, placeholder: "Taille en cm" %>
        <%= f.input :weight, placeholder: "Poids en kg" %>
        <%= f.input :gender, placeholder: "Masculin / Féminin" %>
        <%# <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <div class="d-flex justify-content-around">
        <%= f.submit "Update", class: "btn-grad font" %>
      <% end %>
      <%= link_to "Retour profil patient", patient_path(@patient.id), class: "btn-grad font" %>
      </div>
    </div>
</div>

app/views/patients/index.html.erb
<%= link_to 'Nouveau Patient', new_patient_path, class: "btn btn-primary" %>

app/views/patients/new.html.erb
<h1>Ajouter un Nouveau patient</h1>

<div class="container">
  <div class="row">
    <div class="col">
      <%= simple_form_for @patient do |f| %>
        <%= f.input :first_name, placeholder: "Prénom(s)" %>
        <%= f.input :last_name, placeholder: "Nom(s) de famille" %>
        <%= f.input :birthday, start_year: Date.today.year - 110, end_year: Date.today.year,  placeholder: "YYYY/mm/dd" %>
        <%= f.input :social_security_number, placeholder: "Numéro de sécurité social" %>
        <%= f.input :pathology, placeholder: "ALD" %>
        <%= f.input :height, placeholder: "Taille en cm" %>
        <%= f.input :weight, placeholder: "Poids en kg" %>
        <%= f.input :gender, :collection => ["masculin", "féminin"] %>
        <%# <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit "Create patient", class: "btn btn-primary" %>
      <% end %>
    </div>
      <%= link_to "Acceuil", root_path(@patient), class: "btn-grad font" %><br />
  </div>
</div>

app/views/patients/show.html.erb
<h1 class="h6-3 text-center mb-4"><%= "#{@patient.first_name} #{@patient.last_name}" %></h1>

<div class="container d-flex justify-content-around my-4">
  <%= link_to 'Consultation', new_patient_consultation_path(@patient.id), class: "btn-grad font" %>
  <%= link_to 'Editer profil', edit_patient_path(@patient.id) , class: "btn-grad font" %>
   <%= link_to 'Fil de discussion', chatroom_path(@chatroom.id) , class: "btn-grad font" %>
</div>

<div class="row justify-content-center">
  <div class="col-sm-10">
    <div class="card-product">
      <% @consultations.each do |consultation| %>
        <%= link_to consultation_path(consultation.id) do %>
          <div class="card-product-infos">
              <%= image_tag "ordonnance_test.png" %>
              <div class = "text-group">
                <h6><%= consultation.title %></h6>
                <h6><%= consultation.ald %></h6>
                <h6><%= consultation.content %></h6>
              </div>
            <%= image_tag "3-dots-icon.png", id: "dots" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>